var app = angular.module('myApp', ['angularUtils.directives.dirPagination']);
app.controller('GPAdviceController', function ($scope, $http, $filter) {
    $http.defaults.headers.common.Authorization = 'Basic ' + $('#myEmpUnqId').val(); $scope.currentPage = 1; $scope.itemsPerPage = 25; $scope.alluserlist = []; $scope._Conpath = ''; var url_string = window.location.href; var url = new URL(url_string); var urlhost = url.hostname; var urlprotocol = url.protocol; $(document).ready(function () { if (typeof (_ConPath) === "undefined") { return; } else { if (urlhost === _URLHostName) { $scope._Conpath = _ConPath; } else { $scope._Conpath = urlprotocol + "//" + urlhost + "/api/"; } }; });
    $scope.GPAdviceInfo; $scope.empdata; var rlsarr = []; var count = 0; jQuery.support.cors = true;
    $scope.ResetView = function () { window.location.reload(true); };
    $scope.GetEmpInfo = function () { var emp = new XMLHttpRequest(); emp.open('GET', $scope._Conpath + 'Employee/GetEmployee?empunqid=' + $('#myEmpUnqId').val(), true); emp.setRequestHeader('Accept', 'application/json'); emp.onreadystatechange = function () { if (emp.readyState === 4) { var json = JSON.parse(emp.responseText); $scope.empdata = json; $scope.$digest(); }; }; emp.send(); };
    $scope.GetRelesaseStrategy = function () { var rel = new XMLHttpRequest(); rel.open('GET', $scope._Conpath + 'ReleaseStrategy/GetReleaseStrategy?releaseGroup=' + $('#releaseGroupCode').val() + '&empUnqId=' + $('#myEmpUnqId').val(), true); rel.setRequestHeader('Accept', 'application/json'); rel.onreadystatechange = function () { if (rel.readyState === 4) { var jsonvar1 = JSON.parse(rel.responseText); $scope.rlsdata = jsonvar1; $scope.$digest(); }; }; rel.send(); };
    //Add New Material
    $scope.AddMaterial = function (entity, editflag) {
        if ((typeof (entity) === "undefined") || (typeof (entity.MaterialCode) === "undefined") || (typeof (entity.MaterialDesc) === "undefined") || (typeof (entity.MaterialQty) === "undefined") || (typeof (entity.ApproxValue) === "undefined") || (typeof (entity.HsnCode) === "undefined")) { alert("Please Fill All Required Details Step by Step..."); return false; };
        if (editflag === false) { var tables = document.getElementById('aliasTable'); var rowCounts = tables.rows.length; for (var i = 0; i < rowCounts; i++) { count++; $('.tempRow').remove(); var row = $("<tr>" + "<td style='text-align:center;'><input type='hidden' name='GpAdviceItem' value='" + count + "'>" + count + "</td>" + "<td style='text-align:center;'><input type='hidden' name='MaterialCode' value='" + entity.MaterialCode + "'>" + entity.MaterialCode + "</td>" + "<td style='text-align:left;'><input type='hidden' name='MaterialDesc' value='" + entity.MaterialDesc + "'>" + entity.MaterialDesc + "</td>" + "<td style='text-align:center;'><input type='hidden' name='MaterialQty' value='" + entity.MaterialQty + "'>" + entity.MaterialQty + "</td>" + "<td style='text-align:center;'><input type='hidden' name='ApproxValue' value='" + entity.ApproxValue + "'>" + entity.ApproxValue + "</td>" + "<td style='text-align:center;'><input type='hidden' name='HsnCode' value='" + entity.HsnCode + "'>" + entity.HsnCode + "</td>" + "</tr>"); $("#aliasTable").append(row); break; }; };
        if (editflag === true) { var tables = document.getElementById('editTable'); var rowCounts = tables.rows.length; for (var i = 0; i <= rowCounts; i++) { count++; $('.tempRow').remove(); var row = $("<tr>" + "<td style='text-align:center;'><input type='hidden' name='GpAdviceItem' value='" + rowCounts + "'>" + rowCounts + "</td>" + "<td style='text-align:center;'><input type='hidden' name='MaterialCode' value='" + entity.MaterialCode + "'>" + entity.MaterialCode + "</td>" + "<td style='text-align:left;'><input type='hidden' name='MaterialDesc' value='" + entity.MaterialDesc + "'>" + entity.MaterialDesc + "</td>" + "<td style='text-align:center;'><input type='hidden' name='MaterialQty' value='" + entity.MaterialQty + "'>" + entity.MaterialQty + "</td>" + "<td style='text-align:center;'><input type='hidden' name='ApproxValue' value='" + entity.ApproxValue + "'>" + entity.ApproxValue + "</td>" + "<td style='text-align:center;'><input type='hidden' name='HsnCode' value='" + entity.HsnCode + "'>" + entity.HsnCode + "</td>" + "</tr>"); $("#editTable").append(row); break; }; };
        document.getElementById("txtMaterialCode").value = ""; document.getElementById("txtMaterialDesc").value = ""; document.getElementById("txtMaterialQty").value = ""; document.getElementById("txtApproxValue").value = ""; document.getElementById("txtHsnCode").value = "";
    };
    //Generate / Update  Gate Pass Advice 
    $scope.GenerateGPAdvice = function (data, editflag) {
        var d2 = new Date(); var year = d2.getFullYear().toString(); var month = d2.getMonth() + 1; var yearmonth = year + (month.toString()); var today = new Date(d2.getFullYear(), d2.getMonth(), d2.getDate(), d2.getHours(), d2.getMinutes(), d2.getSeconds()); var now = (today.getFullYear()) + '/' + (today.getMonth() + 1) + '/' + today.getDate() + ' ' + today.getHours() + ':' + today.getMinutes() + ':' + today.getSeconds();
        var tables; if (editflag === false) { tables = document.getElementById('aliasTable'); }; if (editflag === true) { tables = document.getElementById('editTable'); };
        var jsonObj = {}; var TableData = storeTblValues(); TableData = JSON.stringify(TableData);
        function storeTblValues() {
            var TableData = new Array();
            if (editflag === false) {
                $('#aliasTable tr').each(function (row, tr) { TableData[row] = { "yearMonth": yearmonth, "gpAdviceNo": 0, "gpAdviceItem": $(tr).find('td:eq(0)').text(), "materialCode": $(tr).find('td:eq(1)').text(), "materialDesc": $(tr).find('td:eq(2)').text(), "materialQty": $(tr).find('td:eq(3)').text(), "approxValue": $(tr).find('td:eq(4)').text(), "hsnCode": $(tr).find('td:eq(5)').text() } });
                jsonObj.gpAdviceNo = 0; jsonObj.gpAdviceDate = now; jsonObj.gpAdviceType = data.GpAdviceType; jsonObj.purpose = data.Purpose; jsonObj.workOrderNo = data.WorkOrderNo; jsonObj.vendorCode = data.VenderCode; jsonObj.vendorName = data.VenderName; jsonObj.vendorAddress1 = data.VenderAddress1; jsonObj.vendorAddress2 = data.VenderAddress2; jsonObj.vendorAddress3 = data.VenderAddress3; jsonObj.approxDateOfReturn = data.ApproxDt; jsonObj.modeOfTransport = data.ModeOfTransport; jsonObj.transporterName = data.TransporterName; jsonObj.empUnqId = $scope.empdata[0]['empUnqId']; jsonObj.unitCode = $scope.empdata[0]['unitCode']; jsonObj.deptCode = $scope.empdata[0]['deptCode']; jsonObj.statCode = $scope.empdata[0]['statCode']; jsonObj.addDt = now; jsonObj.addUser = $('#myEmpUnqId').val();
            };
            if (editflag === true) {
                $('#editTable tr').each(function (row, tr) { TableData[row] = { "yearMonth": yearmonth, "gpAdviceNo": $('#gpAdviceNo').val(), "gpAdviceItem": $(tr).find('td:eq(0)').text(), "materialCode": $(tr).find('td:eq(1)').text(), "materialDesc": $(tr).find('td:eq(2)').text(), "materialQty": $(tr).find('td:eq(3)').text(), "approxValue": $(tr).find('td:eq(4)').text(), "hsnCode": $(tr).find('td:eq(5)').text() } });
                jsonObj.gpAdviceNo = $('#gpAdviceNo').val(); jsonObj.gpAdviceDate = $scope.pdata[0]['gpAdviceDate'];; jsonObj.gpAdviceType = $('#GpAdviceType').val(); jsonObj.purpose = $('#txtPurpose').val(); jsonObj.workOrderNo = $('#txtWONO').val(); jsonObj.vendorCode = $('#txtVenderCode').val(); jsonObj.vendorName = $('#txtVenderName').val(); jsonObj.vendorAddress1 = $('#txtVenderAdd1').val(); jsonObj.vendorAddress2 = $('#txtVenderAdd2').val(); jsonObj.vendorAddress3 = $('#txtVenderAdd3').val(); jsonObj.approxDateOfReturn = $('#ApproxDt').val(); jsonObj.modeOfTransport = $('#txtModeOfTransport').val(); jsonObj.transporterName = $('#txtTransporterName').val(); jsonObj.empUnqId = $scope.pdata[0]['empUnqId']; jsonObj.unitCode = $scope.pdata[0]['unitCode']; jsonObj.deptCode = $scope.pdata[0]['deptCode']; jsonObj.statCode = $scope.pdata[0]['statCode']; jsonObj.updDt = now; jsonObj.updUser = $('#myEmpUnqId').val();
            }; TableData.shift(); jsonObj.yearMonth = yearmonth; jsonObj.gpAdviceStatus = "N"; jsonObj.releaseGroupCode = "GA"; jsonObj.gaReleaseStrategy = $('#myEmpUnqId').val(); jsonObj.releaseStatusCode = "N"; jsonObj.gpAdviceDetails = TableData; return jsonObj;
        };
        var xhr = new XMLHttpRequest(); if (editflag === false) { xhr.open('POST', $scope._Conpath + 'GpAdvice/CreateGpAdvice', true); }; if (editflag === true) { xhr.open('PUT', $scope._Conpath + 'GpAdvice/UpdateGpAdvice', true); };
        xhr.setRequestHeader("Content-type", "application/json"); xhr.onreadystatechange = function () {
            if (xhr.readyState === 4 && xhr.status === 201) {
                document.getElementById("MessageBox").innerHTML = "<div class='alert alert-success alert-dismissable'><a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a>" + "<strong>Gate Pass Advice Generated Successfully...</strong></div>"; $('#MessageBox').show();
                if (editflag === false) { $("#aliasTable").find("tr:not(:first)").remove(); }; if (editflag === true) { $("#editTable").find("tr:not(:first)").remove(); };
                document.getElementById("txtPurpose").value = ""; document.getElementById("txtWONO").value = ""; document.getElementById("txtVenderCode").value = ""; document.getElementById("txtVenderName").value = ""; document.getElementById("txtVenderAdd1").value = ""; document.getElementById("txtVenderAdd2").value = ""; document.getElementById("txtVenderAdd3").value = ""; document.getElementById("ApproxDt").value = ""; document.getElementById("txtModeOfTransport").value = ""; document.getElementById("txtTransporterName").value = ""; document.getElementById("txtMaterialCode").value = ""; document.getElementById("txtMaterialDesc").value = ""; document.getElementById("txtMaterialQty").value = ""; document.getElementById("txtApproxValue").value = ""; document.getElementById("txtHsnCode").value = "";
            } else if (xhr.readyState === 4 && xhr.status === 200) {
                document.getElementById("MessageBox").innerHTML = "<div class='alert alert-success alert-dismissable'><a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a>" + "<strong>Gate Pass Advice Updated Successfully...</strong></div>"; $('#MessageBox').show();
                if (editflag === false) { $("#aliasTable").find("tr:not(:first)").remove(); }; if (editflag === true) { $("#editTable").find("tr:not(:first)").remove(); };
                document.getElementById("txtPurpose").value = ""; document.getElementById("txtWONO").value = ""; document.getElementById("txtVenderCode").value = ""; document.getElementById("txtVenderName").value = ""; document.getElementById("txtVenderAdd1").value = ""; document.getElementById("txtVenderAdd2").value = ""; document.getElementById("txtVenderAdd3").value = ""; document.getElementById("ApproxDt").value = ""; document.getElementById("txtModeOfTransport").value = ""; document.getElementById("txtTransporterName").value = ""; document.getElementById("txtMaterialCode").value = ""; document.getElementById("txtMaterialDesc").value = ""; document.getElementById("txtMaterialQty").value = ""; document.getElementById("txtApproxValue").value = ""; document.getElementById("txtHsnCode").value = "";
            } else { document.getElementById("MessageBox").innerHTML = "<div class='alert alert-danger alert-dismissable'><a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a><strong>Gate Pass Advice not Saved..</strong></div>"; $('#MessageBox').show(); };
        }; xhr.send(TableData);
    };
    //Get Pending GP Advice List for Release
    $scope.GetGPALists = function () { var xhr1 = new XMLHttpRequest(); xhr1.open('GET', $scope._Conpath + 'AppRelease/GetApplReleaseStatus?empUnqId=' + $('#myEmpUnqId').val() + '&releaseGroupCode=GA', true); xhr1.setRequestHeader('Accept', 'application/json'); xhr1.onreadystatechange = function () { if (xhr1.readyState === 4) { var json = JSON.parse(xhr1.responseText); rlsarr = json; $scope.gparlsdata = json; $scope.$digest(); } }; xhr1.send(); };
    //Popup the Model
    $scope.PopulateData = function (gpAdviceNo, yearMonth) { $scope.GetGPAdviceDetails(yearMonth, gpAdviceNo, false); $('#ConformModel').modal('show'); };
    //Popup the Model
    $scope.PopulateEdit = function (gpAdviceNo, yearMonth) { $scope.GetGPAdviceDetails(yearMonth, gpAdviceNo, true); $('#EditModel').modal('show'); };
    //Get GPAdviceDetails
    $scope.GetGPAdviceDetails = function (yearMonth, gpAdviceNo, editflag) { var pdata = new XMLHttpRequest(); pdata.open('GET', $scope._Conpath + 'GpAdvice/GetGpAdvice?yearMonth=' + yearMonth + '&gpAdviceNo=' + gpAdviceNo, true); pdata.setRequestHeader('Accept', 'application/json'); pdata.onreadystatechange = function () { if (pdata.readyState === 4) { var jsonvar1 = JSON.parse(pdata.responseText); $scope.pdata = jsonvar1; $scope.$digest(); if (editflag === true) { $('#GpAdviceType').val($scope.pdata[0].gpAdviceType); $('#ApproxDt').val($scope.pdata[0].approxDateOfReturn.replace("T00:00:00", "")); }; }; }; pdata.send(); };
    //Release GP Advice
    $scope.ReleaseGPAdvice = function (cnt, gpAdviceNo, releaseStatusCode) {
        var rmks = ''; if (releaseStatusCode === "R") { if ((typeof (cnt) === "undefined") || (typeof (cnt.Remarks) === "undefined")) { document.getElementById("MessageBox").innerHTML = "<div class='alert alert-warning alert-dismissable'><a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a><strong>Please Enter Remarks First For Rejection</strong></div>"; $('#MessageBox').show(); return false; } else { rmks = cnt.Remarks; } } else { if ((typeof (cnt) === "undefined")) { rmks = ""; } else { rmks = cnt.Remarks; }; }; var d = new Date(); var strDate = d.getFullYear() + "/" + (d.getMonth() + 1) + "/" + d.getDate();
        // Get Releaser Details From AppReleaseStatus Table
        var detailarr = []; for (var r = 0; r <= rlsarr.length; r++) { var ecode = rlsarr[r]["gpAdviceNo"]; if (ecode == gpAdviceNo) { detailarr = rlsarr[r]["applReleaseStatus"]; break; } };
        var dataarr = []; for (i = 0; i < detailarr.length; i++) { var release_auth = detailarr[i]["releaseAuth"]; if (release_auth === $('#myEmpUnqId').val()) { dataarr = detailarr[i]; break; } };
        var jsonObj = {}; jsonObj.YearMonth = dataarr.yearMonth; jsonObj.ReleaseGroupCode = dataarr.releaseGroupCode; jsonObj.ApplicationId = gpAdviceNo; jsonObj.ReleaseStrategy = dataarr.releaseStrategy; jsonObj.ReleaseStrategyLevel = dataarr.releaseStrategyLevel; jsonObj.ReleaseCode = dataarr.releaseCode; jsonObj.ReleaseStatusCode = dataarr.releaseStatusCode; jsonObj.ReleaseDate = strDate; jsonObj.ReleaseAuth = dataarr.releaseAuth; jsonObj.IsFinalRelease = dataarr.isFinalRelease; jsonObj.Remarks = rmks; jsonObj.LeaveApplications_YearMonth = null; jsonObj.LeaveApplications_LeaveAppId = null; jsonObj = JSON.stringify(jsonObj);
        var xhr2 = new XMLHttpRequest(); xhr2.open('POST', $scope._Conpath + 'AppRelease/UpdateGpStatus?empUnqId=' + $('#myEmpUnqId').val() + '&releaseStatusCode=' + releaseStatusCode + '&releaseGroupCode=GA', true); xhr2.setRequestHeader("Content-type", "application/json");
        xhr2.onreadystatechange = function () { if (xhr2.readyState === 4) { $scope.GetGPALists(); if (releaseStatusCode === 'F') { document.getElementById("MessageBox").innerHTML = "<div class='alert alert-success alert-dismissable'><a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a>" + "<strong>Gate Pass Advice Releasesd Successfully...</strong></div>"; $('#MessageBox').show(); }; if (releaseStatusCode === 'R') { document.getElementById("Remarks").value = ""; document.getElementById("MessageBox").innerHTML = "<div class='alert alert-success alert-dismissable'><a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a> <strong>Gate Pass Advice Rejected Sucesfully.. </strong></div>"; }; $('#MessageBox').show(); } else { $scope.GetGPALists(); if (releaseStatusCode === 'F') { document.getElementById("Remarks").value = ""; document.getElementById("MessageBox").innerHTML = "<div class='alert alert-danger alert-dismissable'><a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a> <strong>Gate Pass Advice Not Approved.. </strong></div>"; }; if (releaseStatusCode === 'R') { document.getElementById("Remarks").value = ""; document.getElementById("MessageBox").innerHTML = "<div class='alert alert-danger alert-dismissable'><a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a> <strong> Gate Pass Advice Not Rejected .. </strong></div>"; }; $('#MessageBox').show(); }; }; xhr2.send(jsonObj);
    };
    //Get GP Advice List generated by user
    $scope.GetGPAListInfo = function () { var xhr3 = new XMLHttpRequest(); xhr3.open('GET', $scope._Conpath + 'GpAdvice/GetGpAdvice?empUnqId=' + $('#myEmpUnqId').val(), true); xhr3.setRequestHeader('Accept', 'application/json'); xhr3.onreadystatechange = function () { if (xhr3.readyState === 4) { var json = JSON.parse(xhr3.responseText); $scope.gpalist = json; $scope.$digest(); } }; xhr3.send(); };
    //Post Gate Pass Advice
    $scope.PostGpAdvice = function (gpAdviceNo, yearMonth, gpAdviceStatus) {
        var remarks = $('#Remarks').val();
        var pst = new XMLHttpRequest();
        if ($('#myUserRole').val() !== "14") { pst.open('Get', $scope._Conpath + 'GPAdvice/GpAdvicePost?yearMonth=' + yearMonth + '&gpAdviceNo=' + gpAdviceNo + '&empUnqId=' + $('#myEmpUnqId').val() + '&gpAdviceStatus=' + gpAdviceStatus + '&remarks=Self Cancelled', true); };
        if ($('#myUserRole').val() === "14") { pst.open('Get', $scope._Conpath + 'GPAdvice/GpAdvicePost?yearMonth=' + yearMonth + '&gpAdviceNo=' + gpAdviceNo + '&empUnqId=' + $('#myEmpUnqId').val() + '&gpAdviceStatus=' + gpAdviceStatus + '&remarks=' + remarks, true); };
        pst.setRequestHeader('Accept', 'application/json'); pst.onreadystatechange = function () { if (pst.readyState === 4 && pst.status === 200) { document.getElementById("MessageBox").innerHTML = "<div class='alert alert-success alert-dismissable'><a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a><strong> Gate Pass Advice Post Successfully... </strong></div>"; $('#MessageBox').show(); } else { document.getElementById("MessageBox").innerHTML = "<div class='alert alert-danger alert-dismissable'><a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a><strong> Gate Pass Advice not Posted... </strong></div>"; $('#MessageBox').show(); }; };
        pst.send();
    };
    //Releaser Gate Pass Advice Report
    $scope.GatePassAdviceReport = function (rptdata) {
        debugger;
        $('#loading').removeClass("deactivediv"); $('#loading').addClass("activediv");
        var FromDate, ToDate; if ((typeof (rptdata) === "undefined") || (typeof (rptdata.FromDt) === "undefined") || (typeof (rptdata.ToDt) === "undefined")) { var date = new Date(); var firstDay = new Date(date.getFullYear(), date.getMonth() - 1, 1); var lastDay = new Date(date.getFullYear(), date.getMonth() + 2, 0); FromDate = firstDay.getFullYear() + '/' + (firstDay.getMonth() + 1) + '/' + firstDay.getDate(); ToDate = lastDay.getFullYear() + '/' + (lastDay.getMonth() + 1) + '/' + (lastDay.getDate()); } else { FromDate = puser.FromDt; ToDate = puser.ToDt; }; var date1 = new Date(FromDate); var date2 = new Date(ToDate); if (date2 < date1) { document.getElementById("MessageBox").innerHTML = "<div class='alert alert-warning alert-dismissable'><a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a> <strong>Please Enter Valid Date Range.. </strong></div>"; $('#MessageBox').show(); return false; };
        var rpt = new XMLHttpRequest();
        rpt.open('GET', $scope._Conpath + 'GpAdvice/GetGpAdvice?empUnqId=' + $('#myEmpUnqId').val() + '&fromDt=' + FromDate + '&toDt=' + ToDate, true);
        rpt.setRequestHeader('Accept', 'application/json');
        rpt.onreadystatechange = function () {
            if (rpt.readyState === 4) {
                var json = JSON.parse(rpt.responseText);
                $scope.gparpt = json; $scope.$digest();
                $('#loading').removeClass("activediv"); $('#loading').addClass("deactivediv");
            }
        }; rpt.send();
    };
    $scope.sort = function (keyname) { $scope.sortKey = keyname; $scope.reverse = !$scope.reverse; }; $scope.exportAllData = function () { setTimeout(function () { $('#loading').removeClass("deactivediv"); $('#loading').addClass("activediv"); var d = new Date(); d = d.getFullYear() + "/" + (d.getMonth() + 1) + "/" + d.getDate(); var FileName = "Gate_Pass_Report_" + d; $scope.JSONToCSVConvertor($scope.GPAdviceInfo, FileName, true); $('#loading').removeClass("activediv"); $('#loading').addClass("deactivediv"); }, 100); }; $scope.JSONToCSVConvertor = function (JSONData, ReportTitle, ShowLabel) { var arrData = typeof JSONData != 'object' ? JSON.parse(JSONData) : JSONData; var CSV = ''; CSV += ReportTitle + '\r\n\n'; if (ShowLabel) { var row = ""; for (var index in arrData[0]) { row += index + ','; }; row = row.slice(0, -1); CSV += row + '\r\n'; }; for (var i = 0; i < arrData.length; i++) { var row = ""; for (var index in arrData[i]) { row += '"' + arrData[i][index] + '",'; } row.slice(0, row.length - 1); CSV += row + '\r\n'; }; if (CSV === '') { alert("Invalid data"); return; }; var fileName = "MyReport_"; fileName += ReportTitle.replace(/ /g, "_"); var uri = 'data:text/csv;charset=utf-8,' + escape(CSV); var link = document.createElement("a"); link.href = uri; link.style = "visibility:hidden"; link.download = fileName + ".csv"; document.body.appendChild(link); link.click(); document.body.removeChild(link); };
});
app.directive("datepicker", function () { return { restrict: "A", require: "ngModel", link: function (scope, elem, attrs, ngModelCtrl) { var updateModel = function (dateText) { scope.$apply(function () { ngModelCtrl.$setViewValue(dateText); }); }; var options = { dateFormat: "yy-mm-dd", onSelect: function (dateText) { updateModel(dateText); } }; elem.datepicker(options); } } });