var app = angular.module("myApp", ["angularUtils.directives.dirPagination"]);
app.controller("PendingLeaveCntroller", function ($scope, $http) {
    $http.defaults.headers.common.Authorization = "Basic " + $("#myEmpUnqId").val(), $scope.currentPage = 1, $scope.itemsPerPage = 50, $scope.alluserlist = [];
    $scope.jsondata;
    var url_string = window.location.href, url = new URL(url_string), urlhost = url.hostname, urlprotocol = url.protocol; var url_port = url.port;
    $scope._Conpath = ''; var loc = $("#myLoc").val();
    $(document).ready(function () {
        if (typeof (_ConPath) === "undefined") { return; } else {
            if (urlhost === _URLHostName) { $scope._Conpath = _ConPath; } else {
                if (loc === "NSK") { $scope._Conpath = urlprotocol + "//" + urlhost + ":" + url_port + "/api/"; }
                else { $scope._Conpath = urlprotocol + "//" + urlhost + "/api/"; };
            };
        };
    });
    //$(document).ready(function () {
    //    "undefined" != typeof _ConPath && (urlhost === _URLHostName ? $scope._Conpath = _ConPath : $scope._Conpath = urlprotocol + "//" + urlhost + "/api/")
    //});
    $scope.ToValidate = function () { var chkFrom = document.getElementById("FromDt"), chkTo = document.getElementById("ToDt"), FromDate = chkFrom.value, ToDate = chkTo.value, date1 = new Date(FromDate), date2 = new Date(ToDate); return date1 > date2 ? (document.getElementById("MessageBox").innerHTML = "<div class='alert alert-warning alert-dismissable'><a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a> <strong>Please Enter Valid Date Range.. </strong></div>", $("#MessageBox").show(), !1) : !0 }, $scope.GetPendingForPostLeaveAppList = function (entity) { var FromDate, ToDate; if ("undefined" == typeof entity || "undefined" == typeof entity.FromDt || "undefined" == typeof entity.ToDt) return !1; FromDate = entity.FromDt, ToDate = entity.ToDt; var date1 = new Date(FromDate), date2 = new Date(ToDate); if (date1 > date2) return document.getElementById("MessageBox").innerHTML = "<div class='alert alert-warning alert-dismissable'><a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a> <strong>Please Enter Valid Date Range.. </strong></div>", $("#MessageBox").show(), !1; $("#loading").removeClass("deactivediv"), $("#loading").addClass("activediv"); var rls = new XMLHttpRequest; rls.open("GET", $scope._Conpath + "LeavePosting/GetLeaves?fromDt=" + FromDate + "&toDt=" + ToDate, !0), rls.setRequestHeader("Accept", "application/json"), rls.onreadystatechange = function () { if (4 === rls.readyState) { $("#loading").removeClass("activediv"), $("#loading").addClass("deactivediv"), $scope.jsondata = rls.responseText; var json = JSON.parse(rls.responseText); $scope.rlsdata = json, $scope.$digest(), setTimeout(function () { var d = new Date; d = d.getFullYear() + "/" + (d.getMonth() + 1) + "/" + d.getDate(); var FileName = "Pending_For_Post_Leave_App_List_" + d; $scope.JSONToCSVConvertor($scope.jsondata, FileName, !0) }, 100) } }, rls.send() }, $scope.JSONToCSVConvertor = function (JSONData, ReportTitle, ShowLabel) { var arrData = "object" != typeof JSONData ? JSON.parse(JSONData) : JSONData, CSV = ""; if (CSV += ReportTitle + "\r\n\n", ShowLabel) { var row = ""; for (var index in arrData[0]) row += index + ","; row = row.slice(0, -1), CSV += row + "\r\n" } for (var i = 0; i < arrData.length; i++) { var row = ""; for (var index in arrData[i]) row += '"' + arrData[i][index] + '",'; row.slice(0, row.length - 1), CSV += row + "\r\n" } if ("" === CSV) return void alert("Invalid data"); var fileName = "MyReport_"; fileName += ReportTitle.replace(/ /g, "_"); var uri = "data:text/csv;charset=utf-8," + escape(CSV), link = document.createElement("a"); link.href = uri, link.style = "visibility:hidden", link.download = fileName + ".csv", document.body.appendChild(link), link.click(), document.body.removeChild(link) }
}), app.directive("datepicker", function () { return { restrict: "A", require: "ngModel", link: function (scope, elem, attrs, ngModelCtrl) { var updateModel = function (dateText) { scope.$apply(function () { ngModelCtrl.$setViewValue(dateText) }) }, options = { dateFormat: "yy-mm-dd", onSelect: function (dateText) { updateModel(dateText) } }; elem.datepicker(options) } } });